name: LemonZero
version: '${project.version}'
main: me.fast.lemonzero.LemonZero
api-version: 1.17
authors: [ AnonymouslyFast, YouCanDream ]
description: Main Plugin for LemonZero
commands:
  balance:
    usage: /balance [player]
    aliases: bal
  economy:
    usage: /economy <add/set/remove> <player> <amount>
    aliases: eco
  pay:
    usage: /pay <player> <amount>
  staffchat:
    usage: /staffchat [message]
    aliases: sc
  clearchat:
    usage: /clearchat
    aliases: cc
  kick:
    usage: /kick <player> [-s] <reason>
  check:
    usage: /check <player>
    description: Checks a players punishment history.
  shop:
    description: Main command for Server!
    usage: <command>
  gmc:
    description: Sets your gamemode to creative!
  gms:
    description: Sets your gamemode to survival!
  gmsp:
    description: Sets your gamemode to spectator!
  fly:
    description: Turns on/off fly mode!
  help:
    description: Get help about certain things!
  tp:
    description: Teleport around the server!
    aliaes:
      - teleport
  tphere:
    description: Teleport a player to you!
    aliases:
      - teleporthere
  broadcast:
    description: Broadcast a message to the server!
    aliases:
      - bc
  rules:
    description: See the rules of the server.
  afk:
    description: Toggle your AFK status!
  sethome:
    description: Set your home!
  home:
    description: Go to your home!
  delhome:
    description: Delete your home!
  slapi:
    description: SLAPI for life!
    permission: slapi.use
    permission-message: &cThis command is disabled!
  setspawn:
    description: Set the server Spawn
    permission: lemoncore.setspawn
    permission-message: &cNo permission!
  spawn:
    description: Go to spawn!
  verify:
    usage: <command>
    description: get a unique code to verify your discord account to minecraft for rewards!


